export interface Stadium {
  id: string;
  name: string;
  city: string;
  country: 'USA' | 'Canada' | 'Mexico';
  lat: number;
  lng: number;
  capacity: number;
  imageUrl: string;
  timezone: string;
  builtYear: number;
  isNewConstruction?: boolean;
  description: string;
}

export const stadiums: Stadium[] = [
  {
    id: 'metlife',
    name: 'MetLife Stadium',
    city: 'East Rutherford, NJ',
    country: 'USA',
    lat: 40.8135,
    lng: -74.0745,
    capacity: 82500,
    imageUrl: '/stadiums/metlife.png',
    timezone: 'America/New_York',
    builtYear: 2010,
    description: 'Sede de la Final del Mundial 2026. Estadio sin techo compartido por los Giants y Jets de la NFL. Sin obras de remodelación específicas para el torneo.',
  },
  {
    id: 'att',
    name: 'AT&T Stadium',
    city: 'Arlington, TX',
    country: 'USA',
    lat: 32.7473,
    lng: -97.0945,
    capacity: 80000,
    imageUrl: '/stadiums/att.jpg',
    timezone: 'America/Chicago',
    builtYear: 2009,
    description: 'Hogar de los Dallas Cowboys. Famoso por su techo retráctil y la pantalla de vídeo colgante más grande del mundo (160 m de largo). Sin obras adicionales para 2026.',
  },
  {
    id: 'hard-rock',
    name: 'Hard Rock Stadium',
    city: 'Miami Gardens, FL',
    country: 'USA',
    lat: 25.958,
    lng: -80.2389,
    capacity: 65326,
    imageUrl: '/stadiums/hard-rock.png',
    timezone: 'America/New_York',
    builtYear: 1987,
    description: 'Sede de los Miami Dolphins. Renovado en 2016 por USD 550 M con nueva cubierta perimetral y mejoras en hospitalidad. Sede de semifinal del Mundial.',
  },
  {
    id: 'sofi',
    name: 'SoFi Stadium',
    city: 'Inglewood, CA',
    country: 'USA',
    lat: 33.9535,
    lng: -118.3392,
    capacity: 70240,
    imageUrl: '/stadiums/sofi.jpg',
    timezone: 'America/Los_Angeles',
    builtYear: 2020,
    isNewConstruction: true,
    description: 'Inaugurado en 2020, construido desde cero por USD 5.500 M. El estadio más moderno y costoso de la historia. Sede de Rams y Chargers. No requirió obras para el Mundial.',
  },
  {
    id: 'lincoln-financial',
    name: 'Lincoln Financial Field',
    city: 'Philadelphia, PA',
    country: 'USA',
    lat: 39.9008,
    lng: -75.1675,
    capacity: 69176,
    imageUrl: '/stadiums/lincoln-financial.jpg',
    timezone: 'America/New_York',
    builtYear: 2003,
    description: 'Estadio de los Philadelphia Eagles. Inaugurado en 2003. Se realizaron mejoras en infraestructura y servicios para el Mundial, sin ampliación de capacidad.',
  },
  {
    id: 'lumen',
    name: 'Lumen Field',
    city: 'Seattle, WA',
    country: 'USA',
    lat: 47.5952,
    lng: -122.3316,
    capacity: 69000,
    imageUrl: '/stadiums/lumen.jpg',
    timezone: 'America/Los_Angeles',
    builtYear: 2002,
    description: 'Casa de los Seattle Seahawks desde 2002. Considerado uno de los estadios más ruidosos del mundo gracias a su diseño que amplifica el sonido. Sin obras estructurales para 2026.',
  },
  {
    id: 'nrg',
    name: 'NRG Stadium',
    city: 'Houston, TX',
    country: 'USA',
    lat: 29.6847,
    lng: -95.4107,
    capacity: 72220,
    imageUrl: '/stadiums/nrg.jpg',
    timezone: 'America/Chicago',
    builtYear: 2002,
    description: 'Primer estadio de la NFL con techo retráctil (2002). Hogar de los Houston Texans. El techo controlado permite jugar con cualquier condición climática.',
  },
  {
    id: 'mercedes-benz',
    name: 'Mercedes-Benz Stadium',
    city: 'Atlanta, GA',
    country: 'USA',
    lat: 33.7554,
    lng: -84.401,
    capacity: 71000,
    imageUrl: '/stadiums/mercedes-benz.jpg',
    timezone: 'America/New_York',
    builtYear: 2017,
    isNewConstruction: true,
    description: 'Inaugurado en 2017. Famoso por su techo retráctil en forma de pétalos — ocho paneles que se abren como el iris de un ojo. Sede de Atlanta Falcons (NFL) y Atlanta United (MLS). Uno de los estadios más modernos de los EE.UU.',
  },
  {
    id: 'gillette',
    name: 'Gillette Stadium',
    city: 'Foxborough, MA',
    country: 'USA',
    lat: 42.0909,
    lng: -71.2643,
    capacity: 65878,
    imageUrl: '/stadiums/gillette.jpg',
    timezone: 'America/New_York',
    builtYear: 2002,
    description: 'Hogar de los New England Patriots desde 2002. Estadio histórico del fútbol americano en el noreste de los EE.UU. Se realizaron adecuaciones menores de infraestructura para el Mundial.',
  },
  {
    id: 'arrowhead',
    name: 'Arrowhead Stadium',
    city: 'Kansas City, MO',
    country: 'USA',
    lat: 39.0489,
    lng: -94.4839,
    capacity: 76416,
    imageUrl: '/stadiums/arrowhead.jpg',
    timezone: 'America/Chicago',
    builtYear: 1972,
    description: 'Inaugurado en 1972 y renovado completamente en 2010. Sede de los Kansas City Chiefs. Reconocido como uno de los estadios más ruidosos del mundo con récord Guinness. Para el Mundial se realizaron mejoras en accesibilidad y servicios.',
  },
  {
    id: 'levis',
    name: "Levi's Stadium",
    city: 'Santa Clara, CA',
    country: 'USA',
    lat: 37.4033,
    lng: -121.9694,
    capacity: 68500,
    imageUrl: '/stadiums/levis.jpg',
    timezone: 'America/Los_Angeles',
    builtYear: 2014,
    description: 'Inaugurado en 2014 en Silicon Valley, sede de los San Francisco 49ers. Estadio multifuncional con tecnología de punta. Sin obras adicionales para el Mundial.',
  },
  {
    id: 'bc-place',
    name: 'BC Place',
    city: 'Vancouver, BC',
    country: 'Canada',
    lat: 49.2768,
    lng: -123.112,
    capacity: 54500,
    imageUrl: '/stadiums/bc-place.jpg',
    timezone: 'America/Vancouver',
    builtYear: 1983,
    description: 'Inaugurado en 1983. En 2011 recibió una renovación integral de CAD 563 M que incluyó la instalación de un techo retráctil, nuevo marcador y modernización general. Principal estadio del fútbol canadiense.',
  },
  {
    id: 'bmo',
    name: 'BMO Field',
    city: 'Toronto, ON',
    country: 'Canada',
    lat: 43.6332,
    lng: -79.4186,
    capacity: 45000,
    imageUrl: '/stadiums/bmo.jpg',
    timezone: 'America/Toronto',
    builtYear: 2007,
    description: 'La "casa" de la Selección de Canadá. Inaugurado en 2007 con 20.000 plazas, ampliado en 2010 y 2016. Para el Mundial 2026 se construyó una expansión temporal que eleva la capacidad a ~45.000 plazas, cumpliendo con los requisitos FIFA.',
  },
  {
    id: 'azteca',
    name: 'Estadio Azteca',
    city: 'Ciudad de México',
    country: 'Mexico',
    lat: 19.3029,
    lng: -99.1505,
    capacity: 87523,
    imageUrl: '/stadiums/azteca.jpg',
    timezone: 'America/Mexico_City',
    builtYear: 1966,
    description: 'Único estadio en albergar tres Finales de Copa del Mundo (1970, 1986 y 2026). En 2024 comenzó una renovación de USD 160 M que incluye nuevas tribunas de hospitalidad, mejoras en accesibilidad y modernización de instalaciones para el centenario del torneo.',
  },
  {
    id: 'bbva',
    name: 'Estadio BBVA',
    city: 'Monterrey',
    country: 'Mexico',
    lat: 25.6699,
    lng: -100.2446,
    capacity: 53500,
    imageUrl: '/stadiums/bbva.png',
    timezone: 'America/Monterrey',
    builtYear: 2015,
    isNewConstruction: true,
    description: 'Inaugurado en 2015, hogar de Rayados de Monterrey. Estadio moderno con vistas panorámicas a la Sierra Madre. No requirió obras adicionales para el Mundial.',
  },
  {
    id: 'akron',
    name: 'Estadio Akron',
    city: 'Guadalajara',
    country: 'Mexico',
    lat: 20.6821,
    lng: -103.4625,
    capacity: 49850,
    imageUrl: '/stadiums/akron.jpg',
    timezone: 'America/Mexico_City',
    builtYear: 2010,
    isNewConstruction: true,
    description: 'Inaugurado en 2010, sede de Chivas de Guadalajara (antes llamado Omnilife). Estadio de fútbol puro —sin pista atlética— que ofrece una gran proximidad al campo. No requirió obras estructurales para el Mundial.',
  },
];

export function getStadiumById(id: string): Stadium | undefined {
  return stadiums.find((stadium) => stadium.id === id);
}
