export interface Team {
  code: string;
  name: string;
  nameEs: string;
  primaryColor: string;
  secondaryColor: string;
  flagUrl: string;
  group: string;
}

export const teams: Team[] = [
  // ── Group A: MX, ZA, KR, CZ ──────────────────────────────
  {
    code: 'MX',
    name: 'Mexico',
    nameEs: 'México',
    primaryColor: '#006847',
    secondaryColor: '#CE1126',
    flagUrl: 'https://flagcdn.com/w320/mx.png',
    group: 'A',
  },
  {
    code: 'ZA',
    name: 'South Africa',
    nameEs: 'Sudáfrica',
    primaryColor: '#007A4D',
    secondaryColor: '#FFB612',
    flagUrl: 'https://flagcdn.com/w320/za.png',
    group: 'A',
  },
  {
    code: 'KR',
    name: 'South Korea',
    nameEs: 'Corea del Sur',
    primaryColor: '#CD2E3A',
    secondaryColor: '#0047A0',
    flagUrl: 'https://flagcdn.com/w320/kr.png',
    group: 'A',
  },
  {
    code: 'CZ',
    name: 'Czech Republic',
    nameEs: 'República Checa',
    primaryColor: '#D7141A',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/cz.png',
    group: 'A',
  },

  // ── Group B: CA, BA, QA, CH ──────────────────────────────
  {
    code: 'CA',
    name: 'Canada',
    nameEs: 'Canadá',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/ca.png',
    group: 'B',
  },
  {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    nameEs: 'Bosnia y Herzegovina',
    primaryColor: '#002395',
    secondaryColor: '#FECB00',
    flagUrl: 'https://flagcdn.com/w320/ba.png',
    group: 'B',
  },
  {
    code: 'QA',
    name: 'Qatar',
    nameEs: 'Catar',
    primaryColor: '#8D1B3D',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/qa.png',
    group: 'B',
  },
  {
    code: 'CH',
    name: 'Switzerland',
    nameEs: 'Suiza',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/ch.png',
    group: 'B',
  },

  // ── Group C: BR, MA, HT, GB-SCT ──────────────────────────
  {
    code: 'BR',
    name: 'Brazil',
    nameEs: 'Brasil',
    primaryColor: '#FFDF00',
    secondaryColor: '#009C3B',
    flagUrl: 'https://flagcdn.com/w320/br.png',
    group: 'C',
  },
  {
    code: 'MA',
    name: 'Morocco',
    nameEs: 'Marruecos',
    primaryColor: '#C1272D',
    secondaryColor: '#006233',
    flagUrl: 'https://flagcdn.com/w320/ma.png',
    group: 'C',
  },
  {
    code: 'HT',
    name: 'Haiti',
    nameEs: 'Haití',
    primaryColor: '#00209F',
    secondaryColor: '#D21034',
    flagUrl: 'https://flagcdn.com/w320/ht.png',
    group: 'C',
  },
  {
    code: 'GB-SCT',
    name: 'Scotland',
    nameEs: 'Escocia',
    primaryColor: '#003399',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/gb-sct.png',
    group: 'C',
  },

  // ── Group D: US, PY, AU, TR ──────────────────────────────
  {
    code: 'US',
    name: 'United States',
    nameEs: 'Estados Unidos',
    primaryColor: '#002868',
    secondaryColor: '#BF0A30',
    flagUrl: 'https://flagcdn.com/w320/us.png',
    group: 'D',
  },
  {
    code: 'PY',
    name: 'Paraguay',
    nameEs: 'Paraguay',
    primaryColor: '#DA121A',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/py.png',
    group: 'D',
  },
  {
    code: 'AU',
    name: 'Australia',
    nameEs: 'Australia',
    primaryColor: '#FFCD00',
    secondaryColor: '#00843D',
    flagUrl: 'https://flagcdn.com/w320/au.png',
    group: 'D',
  },
  {
    code: 'TR',
    name: 'Turkey',
    nameEs: 'Turquía',
    primaryColor: '#E30A17',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/tr.png',
    group: 'D',
  },

  // ── Group E: DE, CW, CI, EC ──────────────────────────────
  {
    code: 'DE',
    name: 'Germany',
    nameEs: 'Alemania',
    primaryColor: '#FFFFFF',
    secondaryColor: '#000000',
    flagUrl: 'https://flagcdn.com/w320/de.png',
    group: 'E',
  },
  {
    code: 'CW',
    name: 'Curaçao',
    nameEs: 'Curazao',
    primaryColor: '#002B7F',
    secondaryColor: '#F9E03B',
    flagUrl: 'https://flagcdn.com/w320/cw.png',
    group: 'E',
  },
  {
    code: 'CI',
    name: 'Ivory Coast',
    nameEs: 'Costa de Marfil',
    primaryColor: '#FF8200',
    secondaryColor: '#009639',
    flagUrl: 'https://flagcdn.com/w320/ci.png',
    group: 'E',
  },
  {
    code: 'EC',
    name: 'Ecuador',
    nameEs: 'Ecuador',
    primaryColor: '#FFD100',
    secondaryColor: '#003DA5',
    flagUrl: 'https://flagcdn.com/w320/ec.png',
    group: 'E',
  },

  // ── Group F: NL, JP, SE, TN ──────────────────────────────
  {
    code: 'NL',
    name: 'Netherlands',
    nameEs: 'Países Bajos',
    primaryColor: '#FF6600',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/nl.png',
    group: 'F',
  },
  {
    code: 'JP',
    name: 'Japan',
    nameEs: 'Japón',
    primaryColor: '#000080',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/jp.png',
    group: 'F',
  },
  {
    code: 'SE',
    name: 'Sweden',
    nameEs: 'Suecia',
    primaryColor: '#006AA7',
    secondaryColor: '#FECC02',
    flagUrl: 'https://flagcdn.com/w320/se.png',
    group: 'F',
  },
  {
    code: 'TN',
    name: 'Tunisia',
    nameEs: 'Túnez',
    primaryColor: '#E70013',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/tn.png',
    group: 'F',
  },

  // ── Group G: BE, EG, IR, NZ ──────────────────────────────
  {
    code: 'BE',
    name: 'Belgium',
    nameEs: 'Bélgica',
    primaryColor: '#ED2939',
    secondaryColor: '#000000',
    flagUrl: 'https://flagcdn.com/w320/be.png',
    group: 'G',
  },
  {
    code: 'EG',
    name: 'Egypt',
    nameEs: 'Egipto',
    primaryColor: '#CE1126',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/eg.png',
    group: 'G',
  },
  {
    code: 'IR',
    name: 'Iran',
    nameEs: 'Irán',
    primaryColor: '#FFFFFF',
    secondaryColor: '#DA0000',
    flagUrl: 'https://flagcdn.com/w320/ir.png',
    group: 'G',
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    nameEs: 'Nueva Zelanda',
    primaryColor: '#FFFFFF',
    secondaryColor: '#000000',
    flagUrl: 'https://flagcdn.com/w320/nz.png',
    group: 'G',
  },

  // ── Group H: ES, CV, SA, UY ──────────────────────────────
  {
    code: 'ES',
    name: 'Spain',
    nameEs: 'España',
    primaryColor: '#AA151B',
    secondaryColor: '#F1BF00',
    flagUrl: 'https://flagcdn.com/w320/es.png',
    group: 'H',
  },
  {
    code: 'CV',
    name: 'Cape Verde',
    nameEs: 'Cabo Verde',
    primaryColor: '#003893',
    secondaryColor: '#CF2027',
    flagUrl: 'https://flagcdn.com/w320/cv.png',
    group: 'H',
  },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    nameEs: 'Arabia Saudí',
    primaryColor: '#006C35',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/sa.png',
    group: 'H',
  },
  {
    code: 'UY',
    name: 'Uruguay',
    nameEs: 'Uruguay',
    primaryColor: '#5CBFEB',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/uy.png',
    group: 'H',
  },

  // ── Group I: FR, SN, IQ, NO ──────────────────────────────
  {
    code: 'FR',
    name: 'France',
    nameEs: 'Francia',
    primaryColor: '#002395',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/fr.png',
    group: 'I',
  },
  {
    code: 'SN',
    name: 'Senegal',
    nameEs: 'Senegal',
    primaryColor: '#009639',
    secondaryColor: '#FDEF42',
    flagUrl: 'https://flagcdn.com/w320/sn.png',
    group: 'I',
  },
  {
    code: 'IQ',
    name: 'Iraq',
    nameEs: 'Irak',
    primaryColor: '#CE1126',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/iq.png',
    group: 'I',
  },
  {
    code: 'NO',
    name: 'Norway',
    nameEs: 'Noruega',
    primaryColor: '#EF2B2D',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/no.png',
    group: 'I',
  },

  // ── Group J: AR, DZ, AT, JO ──────────────────────────────
  {
    code: 'AR',
    name: 'Argentina',
    nameEs: 'Argentina',
    primaryColor: '#74ACDF',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/ar.png',
    group: 'J',
  },
  {
    code: 'DZ',
    name: 'Algeria',
    nameEs: 'Argelia',
    primaryColor: '#006233',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/dz.png',
    group: 'J',
  },
  {
    code: 'AT',
    name: 'Austria',
    nameEs: 'Austria',
    primaryColor: '#ED2939',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/at.png',
    group: 'J',
  },
  {
    code: 'JO',
    name: 'Jordan',
    nameEs: 'Jordania',
    primaryColor: '#007A3D',
    secondaryColor: '#CE1126',
    flagUrl: 'https://flagcdn.com/w320/jo.png',
    group: 'J',
  },

  // ── Group K: PT, CD, UZ, CO ──────────────────────────────
  {
    code: 'PT',
    name: 'Portugal',
    nameEs: 'Portugal',
    primaryColor: '#FF0000',
    secondaryColor: '#006600',
    flagUrl: 'https://flagcdn.com/w320/pt.png',
    group: 'K',
  },
  {
    code: 'CD',
    name: 'DR Congo',
    nameEs: 'RD del Congo',
    primaryColor: '#007FFF',
    secondaryColor: '#F7D618',
    flagUrl: 'https://flagcdn.com/w320/cd.png',
    group: 'K',
  },
  {
    code: 'UZ',
    name: 'Uzbekistan',
    nameEs: 'Uzbekistán',
    primaryColor: '#FFFFFF',
    secondaryColor: '#1EB53A',
    flagUrl: 'https://flagcdn.com/w320/uz.png',
    group: 'K',
  },
  {
    code: 'CO',
    name: 'Colombia',
    nameEs: 'Colombia',
    primaryColor: '#FCD116',
    secondaryColor: '#003893',
    flagUrl: 'https://flagcdn.com/w320/co.png',
    group: 'K',
  },

  // ── Group L: GB-ENG, HR, GH, PA ──────────────────────────
  {
    code: 'GB-ENG',
    name: 'England',
    nameEs: 'Inglaterra',
    primaryColor: '#FFFFFF',
    secondaryColor: '#CF081F',
    flagUrl: 'https://flagcdn.com/w320/gb-eng.png',
    group: 'L',
  },
  {
    code: 'HR',
    name: 'Croatia',
    nameEs: 'Croacia',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    flagUrl: 'https://flagcdn.com/w320/hr.png',
    group: 'L',
  },
  {
    code: 'GH',
    name: 'Ghana',
    nameEs: 'Ghana',
    primaryColor: '#006B3F',
    secondaryColor: '#FCD116',
    flagUrl: 'https://flagcdn.com/w320/gh.png',
    group: 'L',
  },
  {
    code: 'PA',
    name: 'Panama',
    nameEs: 'Panamá',
    primaryColor: '#DA121A',
    secondaryColor: '#003DA5',
    flagUrl: 'https://flagcdn.com/w320/pa.png',
    group: 'L',
  },
];

export function getTeamByCode(code: string): Team | undefined {
  return teams.find((team) => team.code === code);
}
